/******** DO NOT EDIT THIS FILE ********/
#ifndef _RFT_CLIENT_LOGGING_H
#define _RFT_CLIENT_LOGGING_H
#include "rft_client_util.h"

/*
 * exit_err(protocol_t* proto) - exit the client with an error message 
 *      output to stderr that is based on the current state of the 
 *      protocol as specified by the given proto struct.
 * 
 * Further documentation of this function is deliberately omitted - see the 
 * implementation in rft_client_logging.c
 */
void exit_err(protocol_t* proto);

/*
 * exit_err_msg(protocol_t* proto, int init_errno, int line, char* msg) - 
 *      exit the client with the given error message, errno value, source
 *      file line number and other protocol information represented by proto.
 * 
 * Further documentation of this function is deliberately omitted - see the 
 * implementation in rft_client_logging.c
 */
void exit_err_msg(protocol_t* proto, int init_errno, int line, char* msg);

/*
 * exit_err_state(protocol_t* proto, proto_state state, int line) - 
 *      exit the client with the given protocol state source
 *      file line number and other protocol information represented by proto.
 * 
 * Further documentation of this function is deliberately omitted - see the 
 * implementation in rft_client_logging.c
 */
void exit_err_state(protocol_t* proto, proto_state state, int line);

/*
 * log_protocol(protocol_t* proto) - log information output to stdout 
 *      based on the current state of the  protocol as specified by the 
 *      given proto struct.
 * 
 * Further documentation of this function is deliberately omitted - see the 
 * implementation in rft_client_logging.c
 */
void log_protocol(protocol_t* proto);

/*
 * print_sep() - print an output separator to stdout
 * 
 * Further documentation of this function is deliberately omitted - see the 
 * implementation in rft_client_logging.c
 */
void print_sep();
    
/*
 * fprint_sep(FILE* stream) - print an output separator to the given file
 *  stream.
 * 
 * Further documentation of this function is deliberately omitted - see the 
 * implementation in rft_client_logging.c
 */
void fprint_sep(FILE* stream);

#endif